version: "3.5"
services:
  db:
    image: postgres
    container_name: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5433"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/search-on-github
    ports:
      - "3000:3000"
    depends_on:
      - db